### ISSUE TITLE
E2E Networks office at Sarita Vihar

### ISSUE THREAD

**Issue by dusual** [pydelhi/venue#1]
Name of Organisation:
----------------------------------

E2E Networks

Point of contact From the Organisation
--------------------------------------

Amit Singh Sethi (https://twitter.com/Dusual)

Venu Location:
----------------------
Awfis, Near Sarita Vihar Metro Station

Coordinates: Maps link/geo coordinates
--------------------------------------

https://www.google.co.in/maps/place/Awfis+Mohan+Cooperative/@28.5262975,77.287371,17z/data=!4m5!3m4!1s0x390ce6b27cda231f:0x7eb40d235e86656d!8m2!3d28.5262975!4d77.289565

Seating fascilities details:

 - No of seats - Largest room has a seating capacity of 40, 4 other rooms with capacity from 4-10
 - Access to Electricity Sockets
Yes each seat has one
 
Do you have a projector or a large presentation Screen?
----------------------------

Should be able to arrange this

Preferred dates:
----------------------------

As soon as available with the people here.

Any more details you would like to provide:
----------------------------

Some time in case any one in the office team wishes to present something. , Saturday is working for some team members so allow them to work undisturbed

**Comment by akshayaurora** [comment]
@rajataaron 18th august or earlier time  available for this ?

@dusual  Timing of 11:00 am to 5 pm suits you? Would you folks be providing lunch/snacks to attendees?

**Comment by dusual** [comment]
@akshayaurora  Yes that should work on a weekend. I think lunch/snacks could be arranged.

**Comment by rajataaron** [comment]
@dusual please share email ID with us so that we can send you a formal mail.

**Comment by dusual** [comment]
@rajataaron Sure, You can use amit.sethi@spikecloud.com

**Comment by akshayaurora** [comment]
confirmed for 18th August.

**Comment by rajataaron** [comment]
@vipulgupta2048 please send a formal mail with all the requirements to @dusual  for the approval and confirmation.

Thanks.

**Comment by vipulgupta2048** [comment]
Done.

**Comment by akshayaurora** [comment]
Closing this issue as this event happened and details have been put up on the Meetup page
