### ISSUE TITLE
proposal for upcoming meet-ups venue 

### ISSUE THREAD

**Issue by gaurav5570** [pydelhi/venue#3]
Name of Organisation:
Broctagon IT Solutions Pvt. Ltd. 
----------------------------------

Point of contact From the Organisation:
Gaurav Pandey
--------------------------------------

Venue Location:
Green Boulevard B9/A Tower A 6th floor, Noida sector 62 
----------------------

Coordinates: Maps link/geo coordinates:
- Also, include how to easily reach the venue (Nearby Metro Stations, landmarks)
https://goo.gl/maps/8AZ6iNC6PdF2
Nearby Metro Station - Kaushambi & Noida city Centre 
--------------------------------------

Seating facilities details:
 - No of seats available - 100
 - Access to Internet - yes 
 - Access to electricity Sockets - yes

 
Do you have a projector or a large presentation Screen?
Yes
----------------------------

Preferred dates with timings:
Any weekend 
---------------------

Any more details you would like to provide:
Facilities that you will get to explore once you plan a meet-up with us are listed below: 
1. 100 people accommodation facility 
2. Guest wi-fi 
3. 10000 sq ft area  
4. Audio and Visual system 
5. Spacious cafeteria 
6. Food & beverages 
7. Spacious meeting & conference room 
8. Stationery and consumables 
9. Recreation area 
Have a look through our office space from a 360 Degree view: https://goo.gl/94x3tg  
---------------

Email ID (for contact purposes only) -  gaurav.pandey@broctagon.com

**Comment by akshayaurora** [comment]
@gaurav5570 thanks for the offer, would the venue be available for 21th March 2020?

**Comment by ditsuke** [comment]
Can we close this now?

**Comment by gaurav-archive** [comment]
yes
